# Generated by Django 3.1.1 on 2020-09-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0002_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
