# Generated by Django 3.1.1 on 2020-09-21 16:44

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0003_auto_20200921_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(max_length=31),
        ),
    ]
