# Generated by Django 3.1.1 on 2020-09-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket_app', '0004_auto_20200921_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='product_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(to='supermarket_app.Product'),
        ),
    ]
